### ISSUE TITLE
Hypothesis testing required?

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/SSCI2016#2]
From the SSCI16 reviews:

"_Aside from visualization, the authors may consider doing some hypothesis testing to see whether the engagement and interactions have any significant results._"

**Comment by tomcrick** [comment]
And again:

"_Figures 3-4 and Table 1 show the large predominance of English over other languages, which may make the entire study weak from a statistical significance viewpoint. As a consequence, most of the findings are intuitive and expected._"

**Comment by nalbishry** [comment]
The main thing we are testing here is if the nature of event is reflected on language uses and communities on Twitter. In this work, we are taking quite different events to examine existence of this relationship. 

?

**Comment by tomcrick** [comment]
Closed, probably not relevant in this context.
