### ISSUE TITLE
Detecting users with high closeness scores

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/SSCI2016#3]
From the SSCI16 reviews:

"_In the conclusion, the authors should explain how to fine-tuned to detect users with high closeness scores._"

**Comment by nalbishry** [comment]
We haven't talked about any 'detection'!! 
Literally, it was just a suggestion to 'mention' users with high closeness scores scores. 
I may add more to this, or just take it out.

**Comment by tomcrick** [comment]
Closed, not relevant.
