### ISSUE TITLE
Causality

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/SSCI2016#4]
From the SSCI16 reviews:

"_For instance, it is not clear if there is a causality relating to the Baltimore protests to identify and categorise communities based only on the trend topic (which is the contribute of the others media such as TV, radio, and web site? How we state that twitter was fundamental?)._"

**Comment by nalbishry** [comment]
We're talking about language communities on twitter. What this has to do with causality!!
Someone is totally lost here, either me or the reviewer!

**Comment by tomcrick** [comment]
Closed
