### ISSUE TITLE
Readability of figures

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/SSCI2016#5]
From SSCI16 reviews:

"_Note also that Figures 3-4 are nearly unreadable --- they should be replaced by tables --- while the remaining figures are somehow illustrative but not much useful for the reader._"

**Comment by tomcrick** [comment]
Potentially issues with readability of Figure 11: _Profile-Posting network graph for #Eurovision_

**Comment by nalbishry** [comment]
is it the text, edges, or the whole figure?

**Comment by tomcrick** [comment]
Closed by @nalbishry and me.
