### ISSUE TITLE
New title?

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/SSCI2016#9]
Perhaps we should make the title less generic? e.g.

"_Interactions of Language Networks and Multilingual Communities during Big Social Events_"

"_Interactions of Language Networks and Multilingual Communities during Big Societal Events_"

"_Interactions of Language Networks and Multilingual Communities during Big Societal Events on Twitter_" 

or we could pinch a nice quote from one of the collected tweets/from the hashtag and use that:

"_<tweet quote>: Interactions of Language Networks and Multilingual Communities on Twitter_"

**Comment by ttryfona** [comment]
The very last one?

**Comment by tomcrick** [comment]
How about this:

"_Come Together!_'': Interactions of Language Networks and Multilingual Communities on Twitter

(also added to paper: "_N.B. The first part of the title of this paper comes from the motto of the 2016 Eurovison Song Contest, which along with the theme artwork was ``inspired by the dandelion, symbolising the power of resistance and resilience but also of regeneration''._"

**Comment by nalbishry** [comment]
"Come Together" I love this one!
it has been used in 642 tweets (out of 3,834,937), in 15 different languages (out of 49 ones). not widely used. Might mention this too?

**Comment by tomcrick** [comment]
We might be fine because it was a) the motto of the 2016 Eurovision Song Contest (and doesn't massively clash with Baltimore protests) and b) links nicely about bringing together language networks/multilingual communities.

Unless you can find any other nice little short phrases that were more widely used?

**Comment by nalbishry** [comment]
Cool, I might throw the hpc a pie to chew later :)

**Comment by tomcrick** [comment]
Good good!
